version: '3.8'

services:
  consumer:
    build: .
    container_name: consumer
    ports:
      - "8082:8080"
    networks:
      - shared_kafka_network
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

networks:
  shared_kafka_network:
    external: true
    name: "poc-alegeri-network"
